### ISSUE TITLE
Image validation

### ISSUE THREAD

**Issue by priyadharshiniraju** [vasanthakumar-a/Apartment_Rental_Rails#12]
There image size validation when apartment image is added

**Comment by vasanthakumar-a** [comment]
I can't understand your issue could you please explain it

**Comment by priyadharshiniraju** [comment]
When I added a image the size of image is not in fixed dimension

**Comment by priyadharshiniraju** [comment]
![image](https://user-images.githubusercontent.com/113513503/198572136-4b7b2abf-8aa6-4075-8085-ca6d90a4e2b6.png)
the issuse is fixed
