### ISSUE TITLE
Pagination error

### ISSUE THREAD

**Issue by priyadharshiniraju** [vasanthakumar-a/Apartment_Rental_Rails#13]
When More pages is given instead of available page it shows empty page with pagination

**Comment by vasanthakumar-a** [comment]
I can't understand your issue could you please explain it

**Comment by priyadharshiniraju** [comment]
In url when I typed page=16 ie not a available page the it shows an empty page

**Comment by priyadharshiniraju** [comment]
![image](https://user-images.githubusercontent.com/113513503/198519312-0a3d2428-32e1-4af0-97ce-da143f757515.png)
THE issue has been solved
