### ISSUE TITLE
Age of building, No.of Bedroom ,No. of Balcony ,No. of Bathroom and rent are of type string

### ISSUE THREAD

**Issue by tusharravindran** [vasanthakumar-a/Apartment_Rental_Rails#14]
The default value is 0 when the input is string, make it a integer input to type for better usability
![image](https://user-images.githubusercontent.com/57782379/198294495-d7a666c4-4684-4d85-9cdd-880a6b393e5e.png)

**Comment by mithun30052001** [comment]
Fixed this error by using a number field for the above given fields instead of a text field
![Screenshot from 2022-10-28 14-44-51](https://user-images.githubusercontent.com/81811776/198551804-10de5559-e126-4392-953a-78c744b0d93d.png)
